"""add_deductions_to_income

Revision ID: 90280e5cd690
Revises: bac0fbf5f81a
Create Date: 2026-06-23 17:55:31.127832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90280e5cd690'
down_revision: Union[str, None] = 'bac0fbf5f81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('income', sa.Column('total_deductions_paise', sa.Integer(), nullable=True))
    op.add_column('income', sa.Column('gross_pay_paise', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'gross_pay_paise')
    op.drop_column('income', 'total_deductions_paise')
    op.drop_column('income', 'deductions')
    # ### end Alembic commands ###
