"""add starting_interest_rate to loans

Revision ID: a75a452fee3a
Revises: da17fa20b77a
Create Date: 2026-06-23 00:30:49.219655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75a452fee3a'
down_revision: Union[str, None] = 'da17fa20b77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('starting_interest_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'starting_interest_rate')
    # ### end Alembic commands ###
