"""add_gold_interest_payments

Revision ID: b516b8b03254
Revises: 840d4e73b007
Create Date: 2026-06-23 08:58:36.856224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b516b8b03254'
down_revision: Union[str, None] = '840d4e73b007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_interest_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_interest_payments_id'), 'gold_interest_payments', ['id'], unique=False)
    op.create_index(op.f('ix_gold_interest_payments_loan_id'), 'gold_interest_payments', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gold_interest_payments_loan_id'), table_name='gold_interest_payments')
    op.drop_index(op.f('ix_gold_interest_payments_id'), table_name='gold_interest_payments')
    op.drop_table('gold_interest_payments')
    # ### end Alembic commands ###
