"""add_credit_cards_and_transactions

Revision ID: bac0fbf5f81a
Revises: b516b8b03254
Create Date: 2026-06-23 09:55:45.852682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac0fbf5f81a'
down_revision: Union[str, None] = 'b516b8b03254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_transactions', sa.Column('is_payment', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_transactions', 'is_payment')
    # ### end Alembic commands ###
