"""add loan_account_number to loans

Revision ID: f0b2fa106f61
Revises: a75a452fee3a
Create Date: 2026-06-23 08:28:01.092843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b2fa106f61'
down_revision: Union[str, None] = 'a75a452fee3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('loan_account_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'loan_account_number')
    # ### end Alembic commands ###
